@startuml

class MonoBehaviour{
}

class LoadingManager{
    -Start()

}

class UILogin{
    +username
    +password
    +buttonLogin
    -OnLogin(Result result, string msg)
}

MonoBehaviour <|-- UILogin

@enduml